project_id = "vfomtvoiivhqjwlfcila"

[functions.create-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false
